max_width = 100
newline_style = "Unix"
reorder_imports = true
binop_separator = "Front"
brace_style = "AlwaysNextLine"
color = "Always"
combine_control_expr = false
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
empty_item_single_line = true
fn_params_layout = "Tall"
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = true
format_macro_matchers = true
format_macro_bodies = false
format_strings = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
inline_attribute_width = 50
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
merge_derives = false
imports_granularity = "One"
normalize_comments = true
normalize_doc_attributes = false
overflow_delimited_expr = true
remove_nested_parens = true
reorder_modules = true
short_array_element_width_threshold = 13
skip_children = false
tab_spaces = 4
trailing_comma = "Never"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
where_single_line = false
ignore = [
    "target/*"
]